CREATE DATABASE [BonosAPP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BonosAPP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BonosAPP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BonosAPP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BonosAPP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BonosAPP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BonosAPP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BonosAPP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BonosAPP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BonosAPP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BonosAPP] SET ARITHABORT OFF 
GO

ALTER DATABASE [BonosAPP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BonosAPP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BonosAPP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BonosAPP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BonosAPP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BonosAPP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BonosAPP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BonosAPP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BonosAPP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BonosAPP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BonosAPP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BonosAPP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BonosAPP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BonosAPP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BonosAPP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BonosAPP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BonosAPP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BonosAPP] SET RECOVERY FULL 
GO

ALTER DATABASE [BonosAPP] SET  MULTI_USER 
GO

ALTER DATABASE [BonosAPP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BonosAPP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BonosAPP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BonosAPP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BonosAPP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BonosAPP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BonosAPP] SET  READ_WRITE 
GO